### ISSUE TITLE
File explorer preview not working in certain view modes

### ISSUE THREAD

**Issue by ghost** [maphew/svg-explorer-extension#12] opened 2019-02-03 07:37 UTC
This report is basically a copy and paste from my superuser forum question [here](https://superuser.com/questions/1401509/how-to-enable-svg-preview-in-file-explorer)

My Windows version is Windows 10 Home (more specifically, update 1809). My computer is x64 system, so I used that version. After installing the extension, I changed the default app, as suggested [here](https://superuser.com/questions/342052/how-to-get-svg-thumbnails-in-windows-explorer?noredirect=1&lq=1) but nothing changed.

I got curious and changed view setting in file explorer and found that when the view is set to Small icons/List/Details, I cannot preview the svg files(icon becomes whatever the default app is), but in other modes, like tiles, I can view the previews. Additionally, I have found that regardless of the view mode, preview in the Details pane(panel at the right edge of the file explorer) works. I have rebooted my pc and restarted explorer through task manager countless times. I also tried to remove the file association for .svg files entirely, hoping that would stop the icons from becoming the default app's. However, The default app just switched to internet explorer and I was not able to fully remove the file association.

**Comment by tibold** [comment] 2019-12-29 17:21
This seems to be the expected behavior. The view settings mentioned only uses icons.

This is consistent with how image thumbnail are displayed in Windows. If you open a folder with images and set the view settings to any of the mentioned ones, only icons are displayed.

I am closing this now, but if you do find any inconsistencies between how regular images thumbnails and svg thumbnails are displayed, please re-open the issue.

**Closed as completed by tibold** 2019-12-29 17:21 UTC
Labels: enhancement
